name: 'Generate Workflows Map'
description: 'Generate an event-workflow map of your workflows so you know which event triggers which actions in a repo'
inputs:
  input:
    description: 'Relative path under $GITHUB_WORKSPACE to the workflows folder.'
    required: true
    default: '.github/workflows'
  output:
    description: 'Relative path under $GITHUB_WORKSPACE to the output .md file.'
    required: true
    default: 'WORKFLOWS.md'
outputs:
  path: 
    description: 'The path to the saved file.'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'map'
  color: 'black'
