name: Lint

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run linter
        run: npx mdv spec/*.md
      
