name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: worflows2md 
      uses: ./
    - uses: EndBug/add-and-commit@v7
      with:
       cwd: ${{env.GITHUB_WORKSPACE}}
