name: Regenerate map for test workflows
on:
  pull_request:
  push:
    branches:
      - main
      - 'release/*'

jobs:
  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: workflows2md
        with:
          input: test-workflows
      - uses: EndBug/add-and-commit@v8.0.2
        with:
          cwd: ${{env.GITHUB_WORKSPACE}}
          add: ${{ steps.workflows2md.outputs.path }}
